version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "react",
    "ember",
    "angularjs",
    "angular",
    "meteor",
    "vue"
  ]

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true

[[transformers]]
name = "php-cs-fixer"
enabled = true